steps:
  - name: docker-build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: https://registry.lajas.tech/v2/
      repo: registry.lajas.tech/geyser
      dockerfile: Dockerfile  # Path to the Dockerfile
      tags: latest
      cache-from: type=registry,ref=registry.lajas.tech/docker-build-cache
      cache-to: type=registry,ref=registry.lajas.tech/docker-build-cache
      username:
        from_secret: registry_username
      password:
        from_secret: registry_token
    when:
      branch: master
      event:
        - push
        - cron
      cron: "Rebuild"

